In [21]:
import numpy as np 

In [22]:
#scores = np.load('Cart_genetic/score_500/serio/scores.npy')
weights = np.load('Cart_genetic/score_500/serio/CartPole-v1-20190119010914.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'Cart_genetic/score_500/serio/CartPole-v1-20190119010914.npy'

In [15]:
print(scores)

[[  0   0   0]
 [ 15  10  10]
 [ 10  10  11]
 [  9  10  10]
 [  9  10   9]
 [  9   9   9]
 [ 10   9   9]
 [ 10   9  10]
 [  9   8   9]
 [ 10   9   9]
 [  9  10   8]
 [ 10  10  11]
 [  9  10   9]
 [ 10   9  11]
 [  8   8  10]
 [  9   9   8]
 [ 10   8  10]
 [ 10   8  10]
 [  9   9  10]
 [ 10  10   8]
 [  9   9   8]
 [ 10  10   9]
 [  9  10  10]
 [  9  11  10]
 [  8  10   9]
 [  9  10   9]
 [ 11  10  10]
 [ 11   9   9]
 [  9   9  10]
 [ 10   9  10]
 [  9  10  10]
 [ 10  10   9]
 [  9  10  10]
 [ 10  10   9]
 [  9   9  10]
 [ 10  10   9]
 [  8  10   9]
 [  9   9   9]
 [  9  10   9]
 [  9   8  11]
 [ 15  14  14]
 [ 16  22  16]
 [ 29  21  32]
 [ 59 134  58]
 [ 27  33  25]
 [ 64  58  99]
 [ 34  50  35]
 [ 30  29  33]
 [ 22  16  19]
 [ 17  27  17]
 [ 25  19  21]
 [ 31  21  40]
 [ 21  20  25]
 [ 23  30  23]
 [ 22  25  23]
 [ 25  25  33]
 [ 26  31  23]
 [ 30  32  26]
 [ 18  21  31]
 [ 22  19  24]
 [ 17  17  19]
 [ 23  24  26]
 [ 16  17  21]
 [ 30  19  28]
 [ 25  26  21]
 [ 30  20  24]
 [ 20  15 

In [16]:
weights.shape

(35297, 4)

In [19]:
best_agent = weights[35296]

In [20]:
np.save('score_500/serio/best_agent_dqn.npy', best_agent)